// src/lib/components/Header.svelte
<script>
    import {writable} from "svelte/store";
    import GoSearch from 'svelte-icons/go/GoSearch.svelte'
    import GoGear from 'svelte-icons/go/GoGear.svelte'

    const searchStore = writable("");
    const placeholderStore = writable("Search...");
    const searchExpanded = writable(false);

    const menuExpanded = writable(false);


    placeholderStore.set("Search is currently disabled");

    function openSearch() {
        if ($searchExpanded) return searchExpanded.set(false);
        searchExpanded.set(true);
    }

    function openMenu() {
        if ($menuExpanded) return menuExpanded.set(false);
        menuExpanded.set(true);
    }
</script>
<div class="header">
    <div class="dropdown-container">
        <button class="dropdown" on:click={openMenu}>
            <div class="icon">
                <GoGear/>
            </div>
            <div class="dropdown-content" style={$menuExpanded ? 'display: block;' : 'display: none;'}>
                <a href="/login">Sign In</a>
                <a href="/register">Sign Up</a>
            </div>
        </button>
    </div>
    <div class="centraliser">
        <ul>
            <li>
                <a href="/archive">
                    <!--          <Icon name="i-fluent-mdl2:archive"/>-->
                    Archives
                </a>
            </li>
            <li>
                <a href="/hosts">
                    <!--          <Icon name="i-material-symbols:person-2-outline"/>-->
                    Hosts
                </a>
            </li>
            <li>
                <a href="/sponsors">
                    <!--          <Icon name="i-mdi:advertisements"/>-->
                    Sponsors
                </a>
            </li>
            <li style="scale: 1.4; margin-top: 5px;">
                <a href="/">
                    <img alt="The WAN Database" src="https://cdn.thewandb.com/assets/WANDB_darkBackground.svg"
                         width="100"/>
                </a>
            </li>
            <li>
                <a href="/products">
                    <!--          <Icon name="i-material-symbols:shopping-bag-outline"/>-->
                    Products
                </a>
            </li>
            <li>
                <a href="/about">
                    <!--          <Icon name="i-mdi:information-outline"/>-->
                    About
                </a>
            </li>
            <li>
                <a href="/contact">
                    <!--          <Icon name="i-material-symbols:person-2-outline"/>-->
                    Contact
                </a>
            </li>
        </ul>
    </div>
    <button class="search" on:click={openSearch} style={$searchExpanded ? 'width: 300px;' : 'width: 42px;'}>
        <div class="icon"
             style={$searchExpanded ? 'visibility: hidden; width: 0px' : 'visibility: visible; width: 42px'}>
            <GoSearch/>
        </div>
        <input bind:value="{$searchStore}" placeholder={$placeholderStore}
               style={$searchExpanded ? 'width: 100%; margin: 0 0.75rem;' : 'width: 0px; margin: 0 0;'}
               type="text"/>
    </button>
</div>
<style>
    .header {
        display: grid;
        grid-template-columns: 320px auto 320px;
        background-color: #000;
        color: #fff;
        padding: 10px 0;
        margin: 5px;
        width: calc(100% - 10px);
        border-radius: 5px;
        position: sticky;
        z-index: 100;
        justify-content: center;
        justify-content: space-around;
    }

    .header .dropdown-container {
        /*width: 200px;*/
        margin-right: auto;
    }

    .header .dropdown {
        width: 200px;
        height: fit-content;
        position: relative;
        display: inline-block;
        flex-direction: column;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 200px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 101;
    }

    .header .search, .header .dropdown-container {
        display: flex;
        align-items: center;
        justify-content: center;
        justify-content: space-around;
        /*width: 300px;*/
        height: 40px;
        background: hsl(0, 0%, 20%);
        border-radius: 20px;
        padding: 0 0.1rem;
        margin: 5px 0 5px auto;
        transition: 200ms;
        border: none;
        color: white;
    }

    .header .dropdown {
        width: 42px;
        margin: 5px auto 5px 0;
    }

    .header .search > input {
        background: none;
        border: none;
        outline: none;
        color: white;
        /*width: 100%;*/
        font-size: 1rem;
        font-weight: 600;
        margin-right: 0.75rem;
        margin-left: 0.75rem;
        transition: 200ms;
    }

    .header .search > input::placeholder {
        color: white;
        font-weight: 500;
    }

    .header .search > .icon, .header .dropdown > .icon {
        width: 22px;
        height: 22px;
        margin: 0 auto;
        transition: 200ms;
    }

    .header ul {
        /*position: relative;*/
        left: 100%;
        transform: translateX(-10%);
        list-style: none;
        margin: 0 auto;
        min-width: 1000px;
        padding: 0;
        display: flex;
        justify-content: space-between;
        align-items: center;

    }

    .header ul li {
        display: inline-block;
        margin: 0 10px;
        font-size: 1.1em;
        font-weight: 500;
        text-transform: uppercase;
        letter-spacing: 1px;
    }

    .header ul li a {
        color: #aaa;
        text-decoration: none;
        transition: 200ms ease-in-out;
    }

    .header ul li a:hover {
        color: #fff;
        text-decoration: underline;
        transition: 200ms ease-in-out;
    }
</style>

// comonents/Header.vue
<script lang="ts" setup>
const search = ref();
const searchText = ref('');
const settingsDropdown = ref();

useAsyncData(async () => {
  // search.value.disabled = true
  search.value.placeholder = 'Search is unavailable.'
}, {
  watch: [search]
})

onMounted(() => {
  window.onclick = (event) => {
    if (!event.target || !("id" in event.target)) return;

    if (event.target !== settingsDropdown.value && event.target.id !== 'header__settings__button') {
      if (settingsDropdown.value.attributes.getNamedItem('opened').value === 'true') {
        toggleDropdown();
      }
    }
  }
})

const toggleDropdown = () => {
  let state = settingsDropdown.value.attributes.getNamedItem('opened');

  if (state.value === 'false') {
    state.value = 'true';
    settingsDropdown.value.style.opacity = '1';
    settingsDropdown.value.style.visibility = 'visible';
    settingsDropdown.value.style.marginTop = '0.5rem';
    settingsDropdown.value.style.width = '300px';
    settingsDropdown.value.style.pointerEvents = 'all';
  } else {
    state.value = 'false';
    settingsDropdown.value.style.opacity = '0';
    settingsDropdown.value.style.visibility = 'hidden';
    settingsDropdown.value.style.marginTop = '0';
    settingsDropdown.value.style.width = '0px';
    settingsDropdown.value.style.pointerEvents = 'none';
  }
  settingsDropdown.value.attributes.setNamedItem(state);


}

</script>
<template>
  <div class="header">
    <div class="header__side">
      <div class="settings">
        <button id="header__settings__button" class="header__settings__button" @click="toggleDropdown">
          <Icon id="header__settings__button" name="i-mdi:settings-outline"/>
        </button>
        <div ref="settingsDropdown" class="dropdown__container" opened="false">
          <div class="dropdown__item">
            <span>
              <Icon name="i-mdi:account-outline"/>
              Account
            </span>
          </div>
          <div class="dropdown__item">
            <span>
              <Icon name="i-mdi:logout"/>
              Logout
            </span>
          </div>
          <div class="dropdown__item">
            <span>
              <Icon name="i-mdi:information-outline"/>
              Theme
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="header__menu left">
      <ul>
        <li>
          <nuxt-link to="/archive">
            <Icon name="i-fluent-mdl2:archive"/>
            Archives
          </nuxt-link>
        </li>
        <li>
          <nuxt-link to="/hosts">
            <Icon name="i-material-symbols:person-2-outline"/>
            Hosts
          </nuxt-link>
        </li>
        <li>
          <nuxt-link to="/sponsors">
            <Icon name="i-mdi:advertisements"/>
            Sponsors
          </nuxt-link>
        </li>
        <li>
          <nuxt-link to="/">
            <img alt="The WAN Database" src="https://cdn.thewandb.com/assets/WANDB_darkBackground.svg" width="100"/>
          </nuxt-link>
        </li>
        <li>
          <nuxt-link to="/products">
            <Icon name="i-material-symbols:shopping-bag-outline"/>
            Products
          </nuxt-link>
        </li>
        <li>
          <nuxt-link to="/about">
            <Icon name="i-mdi:information-outline"/>
            About
          </nuxt-link>
        </li>
        <li>
          <nuxt-link to="/contact">
            <Icon name="i-material-symbols:person-2-outline"/>
            Contact
          </nuxt-link>
        </li>
      </ul>
    </div>
    <div class="header__side">
      <div class="header__search">
        <Icon name="i-mdi:search"/>
        <input ref="search" v-model="searchText" placeholder="Search for anything" type="text">
      </div>
    </div>
  </div>
</template>
<style scoped>
.settings {
  display: flex;
  position: relative;
  top: 60px;
  flex-direction: column;
  padding: 0 0.1rem;
  margin-right: 1rem;
}

.settings > .dropdown__container {
  opacity: 0;
  overflow: hidden;
  visibility: hidden;
  display: flex;
  flex-direction: column;
  top: 100%;
  position: relative;
  width: 300px;

  background: hsl(0, 0%, 20%);
  border-radius: 5px;
  transition: all 0.2s ease-in-out;
}

.settings > .dropdown__container > .dropdown__item {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 300px;
  height: 40px;
  padding: 0 0.1rem;
  margin-right: 1rem;
}

.settings > .dropdown__container > .dropdown__item:hover {
  background: hsl(0, 0%, 30%);
}

.settings > button {
  background: none;
  border: none;
  outline: none;
  cursor: pointer;
  color: white;
  width: 1.5rem;
  height: 1.5rem;
  border-radius: 50%;
  vertical-align: center;
  line-height: 1rem;
  text-align: center;
  transition: all 0.2s ease-in-out;
  font-size: 1.5rem;
  margin-right: 0.5rem;
  margin-left: 0.5rem;
}

.settings > button:hover {
  color: hsl(0, 0%, 50%);
  transition: all 0.2s ease-in-out;
}

.header {
  background: hsl(0, 0%, 10%);
  color: white;
  display: flex;
  position: sticky;
  top: 0;
  z-index: 100;
  align-items: center;
}

.header__search {
  width: auto;
  margin-right: 1.5rem;
}

.header__menu {
  flex: 1;
}

.header__menu > ul {
  display: flex;
  justify-content: space-evenly;
  list-style: none;
  padding: 0;
}

.header__menu > ul > li {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 140px;
  color: white;
  text-transform: uppercase;
  padding: 0.5rem 0.75rem;
  margin: 0 0.25rem;
  cursor: pointer;
  transition: all 0.2s ease-in-out;
  border-radius: 20px;
}

.header__menu > ul > li > a {
  font-weight: 600;
  display: flex;
  align-items: center;
  text-decoration: none;
  width: 140px;
  color: white;
  text-transform: uppercase;
  padding: 0.5rem 1rem;
  cursor: pointer;
  transition: all 0.2s ease-in-out;
}

.header__menu > ul > li > a > svg {
  margin-right: 0.5rem;
}

.header__menu > ul > li:hover {
  background: hsl(0, 0%, 20%);
}

.left {
  margin: 0 auto;
}

.header__side {
  display: flex;
  align-items: center;
  justify-content: left;
  justify-content: space-between;
  width: 300px;
  height: 40px;
  padding: 0 0.1rem;
  margin: 0 1rem;
}

.header__search {
  display: flex;
  align-items: center;
  justify-content: center;
  justify-content: space-around;
  width: 300px;
  height: 40px;
  background: hsl(0, 0%, 20%);
  border-radius: 20px;
  padding: 0 0.1rem;
  margin-right: 1rem;
}

.header__search > input {
  background: none;
  border: none;
  outline: none;
  color: white;
  width: 100%;
  font-size: 1rem;
  font-weight: 600;
  margin-right: 0.75rem;
}

.header__search > input::placeholder {
  color: white;
  font-weight: 600;
}

.header__search > svg {
  color: white;
  font-size: 1.5rem;
  margin-right: 0.5rem;
  margin-left: 0.5rem;
}
</style>
